"""
Report Node
Generates final Markdown intelligence report
"""
from datetime import datetime
from typing import Any

from ..state import AgentState, ThemeGroup


def report_node(state: AgentState) -> dict[str, Any]:
    """
    Report node: Generate final Markdown report

    Args:
        state: Current agent state with themes

    Returns:
        Updated state with report string
    """
    themes: list[ThemeGroup] = state.get('themes', [])
    errors = state.get('errors', [])
    config = state.get('config', {})

    # Build report
    report_lines = []

    # Header
    report_date = datetime.now().strftime('%Y-%m-%d')
    report_lines.append(f"# AI Security Intelligence Report")
    report_lines.append(f"**Date:** {report_date}")
    report_lines.append("")

    # Executive Summary
    report_lines.append("## Executive Summary")
    if themes:
        total_articles = sum(len(t.articles) for t in themes)
        theme_names = [t.theme_name for t in themes]
        report_lines.append(
            f"This report covers {total_articles} articles across "
            f"{len(themes)} themes: {', '.join(theme_names)}."
        )
    else:
        report_lines.append("No articles were processed in this reporting period.")
    report_lines.append("")

    # Theme Sections
    for theme in themes:
        report_lines.append(f"## {theme.theme_name}")
        report_lines.append("")
        report_lines.append(theme.summary)
        report_lines.append("")

        # Articles
        report_lines.append("### Sources")
        for article in theme.articles:
            title = article.title or "Untitled"
            report_lines.append(f"- [{title}]({article.url})")
        report_lines.append("")

        # Security Takeaways
        if theme.security_takeaways:
            report_lines.append("### Security Takeaways")
            for takeaway in theme.security_takeaways:
                report_lines.append(f"- {takeaway}")
            report_lines.append("")

    # Errors Section (if any)
    if errors and config.get('include_errors', True):
        report_lines.append("## Processing Notes")
        report_lines.append("")
        for error in errors:
            report_lines.append(f"- {error}")
        report_lines.append("")

    # Footer
    report_lines.append("---")
    report_lines.append("*Generated by AI Security Intelligence Agent*")

    report = "\n".join(report_lines)

    return {'report': report}
